In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data1.csv')
df.head()

   fever  Bodypain  Age  Runnynose  dif in breathing  infection prob
0    104         1   88          1               1.0               0
1    102         1   27          1              -1.0               1
2     95         0   75          0               0.0               0
3    101         1   72          0              -1.0               1
4    105         0   73          0               1.0               0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fever             999 non-null    int64
 1   Bodypain          999 non-null    int64
 2   Age               999 non-null    int64
 3   Runnynose         999 non-null    int64
 4   dif in breathing  998 non-null    float64
 5   infection prob    999 non-null    int64
dtypes: float64(1), int64(5)
memory usage: 47.0 KB

In [4]:
df['dif in breathing'].value_counts()

-1.0    349
 1.0    343
 0.0    306
Name: dif in breathing, dtype: int64

In [5]:
df.describe()

,fever,Bodypain,Age,Runnynose,dif in breathing,infection prob
count,999.000000,999.00000,999.000000,999.000000,998.000000,999.000000
mean,100.032032,0.49049,50.036036,0.529530,-0.006012,0.469469
std,3.189250,0.50016,29.240464,0.499377,0.833094,0.499317
min,95.000000,0.00000,0.000000,0.000000,-1.000000,0.000000
25%,97.000000,0.00000,25.000000,0.000000,-1.000000,0.000000
50%,100.000000,0.00000,50.000000,1.000000,0.000000,0.000000
75%,103.000000,1.00000,75.500000,1.000000,1.000000,1.000000
max,105.000000,1.00000,100.000000,1.000000,1.000000,1.000000

In [6]:
import numpy as np
df[:] = np.nan_to_num(df)

In [7]:
def data_split(data,ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [8]:
np.random.permutation(7)

array([3, 2, 5, 1, 6, 4, 0])

In [9]:
train,test = data_split(df, 0.2)

In [10]:
train

     fever  Bodypain   Age  Runnynose  dif in breathing  infection prob
423  100.0       1.0  46.0        0.0               0.0             0.0
778  104.0       0.0   5.0        0.0               1.0             1.0
286   99.0       0.0  99.0        0.0              -1.0             0.0
165  100.0       0.0   2.0        0.0               1.0             0.0
960   96.0       0.0  79.0        1.0              -1.0             0.0
..     ...       ...   ...        ...               ...             ...
106   95.0       0.0  44.0        1.0              -1.0             1.0
270  104.0       1.0  36.0        1.0               1.0             0.0
860  103.0       0.0   4.0        1.0               0.0             1.0
435   95.0       0.0  25.0        1.0               0.0             1.0
102   96.0       0.0  70.0        0.0               1.0             0.0

[800 rows x 6 columns]

In [11]:
test

     fever  Bodypain   Age  Runnynose  dif in breathing  infection prob
453  105.0       1.0   9.0        0.0              -1.0             0.0
793   97.0       1.0  31.0        1.0              -1.0             0.0
209  105.0       1.0  94.0        0.0               1.0             0.0
309  105.0       1.0  10.0        1.0               1.0             0.0
740  104.0       1.0  34.0        0.0              -1.0             1.0
..     ...       ...   ...        ...               ...             ...
346  105.0       0.0  47.0        0.0               1.0             0.0
78   103.0       0.0  16.0        0.0              -1.0             1.0
29    99.0       0.0  72.0        0.0               0.0             0.0
277  103.0       1.0  66.0        0.0              -1.0             0.0
261   97.0       0.0   9.0        1.0               1.0             1.0

[199 rows x 6 columns]

In [12]:
X_train = train[['fever','Bodypain','Age','Runnynose','dif in breathing']].to_numpy()
X_test = test[['fever','Bodypain','Age','Runnynose','dif in breathing']].to_numpy()

In [13]:
Y_train = train[['infection prob']].to_numpy().reshape(800 ,)
Y_test = test[['infection prob']].to_numpy().reshape(199 ,)

In [14]:
Y_train

array([0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0.,
       1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 1., 0.,
       0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 0.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1.,
       0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1.,
       0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1.,
       0., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 1.,
       1., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 0.,
       0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1.,
       0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0.,
       1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0.,
       0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1., 0.,
       0., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 1.,
       1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1.,
       0., 1., 0., 0., 1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1.,
       0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0.,
       1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0.,
       1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 1., 1.,
       1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1.,
       1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0.,
       1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1.,
       0.])

In [15]:
from sklearn.linear_model import LogisticRegression

In [16]:
clf = LogisticRegression()
clf.fit(X_train , Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [26]:
inputfeatures = [104,1,22,-1,1]
infProb = clf.predict_proba([inputfeatures])[0][1]

In [27]:
infProb

0.4505056715691755